name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Build the HTML documentation
    - run: echo '::set-env name=doxygen_exclude::src/testfile2.h'
    - run: echo '::set-env name=doxygen_enabled_sections::ALL_DOCS'
    - run: echo '::set-env name=doc_dir::docs_out'
    - run: mkdir -p docs_out
    - run: pwd docs_out
    - run: VER=`grep -i sdk_version src/versions.h | sed 's/\s\+/,/g' | cut -d, -f3`
    - run: VER=`grep -i sdk_version src/versions.h | sed 's/\s\+/,/g' | cut -d, -f3`; VER_MAJOR=`grep -i sdk_major_version src/versions.h | sed 's/\s\+/,/g' | cut -d, -f3`; VER_MINOR=`grep -i sdk_minor_version src/versions.h | sed 's/\s\+/,/g' | cut -d, -f3`; echo '::set-env name=MY_VER::"${VER}_${VER_MAJOR}_${VER_MINOR}"'
    - run: echo $MY_VER
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: ./doc/Doxyfile
          working-directory: .
    - run: ls docs_out
    
    # Deploy the HTML documentation to GitHub Pages
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3.7.0-8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_out/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
        destination_dir: testdir
